chain:
- name: "encoder"
  chain_link_spec_path: "blocks/block_stack"
  cfg:
    input_dim: 784
    output_dim: 2
    hidden_dims: [512]
    ordered_module_specs:
    - {nnmodule_spec_path: "activation/relu", kwargs: {}}
    block_wrapper_name: null
- name: "latent_clustering"
  chain_link_spec_path: "latent/clustering_fuzzy"
  cfg:
    n_components: 20
    latent_dim: 2
    components_std: 1.
    constraint_method: "huber"
    loss_coef_latent_fuzzy_clustering: 0.001
    loss_coef_clustering_component_reg: 0.0001
- name: "decoder"
  chain_link_spec_path: "blocks/block_stack"
  cfg:
    input_dim: 2
    output_dim: 784
    hidden_dims: [512]
    ordered_module_specs:
    - {nnmodule_spec_path: "activation/relu", kwargs: {}}
    block_wrapper_name: null
- name: "output-activation"
  chain_link_spec_path: "blocks/standalone_tiny_module"
  cfg:
    nnmodule_spec_path: "activation/sigmoid"
    kwargs: {}
- name: "rearrange"
  chain_link_spec_path: "misc/rearranger"
  cfg: {}
- name: "reconstr_loss"
  chain_link_spec_path: "loss/reconstruction"
  cfg:
    coef: 1.
    loss_fn: {name: "mse", kwargs: {reduction: "none"}}
    tensor_reductor: {name: "mean", kwargs: {}}
- name: "clone_tensor"
  chain_link_spec_path: "misc/cloner"
  cfg: {}
optimizer: {optimizer_name: "adam", kwargs: {lr: 0.001}}
loss_manager:
  reductions:
  - {reduce_pattern: "b 1 ->", reductor_name: "mean", kwargs: {}}
processing_commands:
- command_name: "forward"
  processing_steps:
  - {link_name: 'clone_tensor', method_name: 'forward', kwargs: {data_name: "img", clone_name: "img_org"}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img", pattern: "b 1 h w -> b (h w)"}}
  - {link_name: 'encoder', method_name: 'forward', kwargs: {data_name: "img"}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img", pattern: "b d -> b 1 d"}}
  - {link_name: 'latent_clustering', method_name: 'forward', kwargs: {data_name: "img"}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img", pattern: "b 1 d -> b d"}}
  - {link_name: 'decoder', method_name: 'forward', kwargs: {data_name: "img"}}
  - {link_name: 'output-activation', method_name: 'forward', kwargs: {data_name: "img"}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img", pattern: "b (h w) -> b 1 h w", h: 28, w: 28}}
  - {link_name: 'reconstr_loss', method_name: 'forward', kwargs: {data_name: "img", target_name: "img_org", reduce_pattern: "b 1 h w ->"}}
- command_name: "encode"
  processing_steps:
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img", pattern: "b 1 h w -> b (h w)"}}
  - {link_name: 'encoder', method_name: 'forward', kwargs: {data_name: "img"}}
