chain:
- name: "encoder"
  chain_link_spec_path: "blocks/block_stack"
  cfg:
    input_dim: 784
    output_dim: 4
    hidden_dims: [512]
    ordered_module_specs:
    - {nnmodule_spec_path: "activation/relu", kwargs: {}}
    block_wrapper_name: null
- name: "posterior"
  chain_link_spec_path: "latent/posterior_gaussian"
  cfg:
    std_transform: "softplus"
    loss_coef_posterior_entropy: .001
- name: "prior"
  chain_link_spec_path: "latent/prior_gaussian_mixture_nll"
  cfg:
    n_components: 10
    latent_dim: 2
    components_std: 1.
    loss_coef_prior_nll: .001
- name: "decoder"
  chain_link_spec_path: "blocks/block_stack"
  cfg:
    input_dim: 2
    output_dim: 784
    hidden_dims: [512]
    ordered_module_specs:
    - {nnmodule_spec_path: "activation/relu", kwargs: {}}
    block_wrapper_name: null
- name: "reconstr_loss"
  chain_link_spec_path: "loss/reconstruction"
  cfg:
    coef: 1.
    loss_fn: {name: "mse", kwargs: {reduction: "none"}}
    tensor_reductor: {name: "mean", kwargs: {}}
- name: "output-activation"
  chain_link_spec_path: "blocks/standalone_tiny_module"
  cfg:
    nnmodule_spec_path: "activation/sigmoid"
    kwargs: {}
- name: "clone-input"
  chain_link_spec_path: "misc/cloner"
  cfg: {}
- name: "rearrange"
  chain_link_spec_path: "misc/rearranger"
  cfg: {}
- name: "repeat"
  chain_link_spec_path: "misc/repeater"
  cfg: {}
optimizer: {optimizer_name: "adam", kwargs: {lr: 0.001}}
loss_manager:
  reductions:
  - {reduce_pattern: "b s -> b", reductor_name: "logsumexp", kwargs: {}}
  - {reduce_pattern: "b ->", reductor_name: "mean", kwargs: {}}
processing_commands:
- command_name: "forward"
  processing_steps:
  - {link_name: 'clone-input', method_name: 'forward', kwargs: {data_name: "img", clone_name: "img_org"}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img", pattern: "b 1 h w -> b (h w)"}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "condition_values", pattern: "b 1 -> b"}}
  - {link_name: 'encoder', method_name: 'forward', kwargs: {data_name: "img"}}
  - {link_name: 'posterior', method_name: 'forward', kwargs: {data_name: "img", n_latent_samples: 16}}
  - {link_name: 'prior', method_name: 'forward', kwargs: {data_name: "img", component_indicator_name: "condition_values"}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img", pattern: "b s d -> (b s) d"}}
  - {link_name: 'decoder', method_name: 'forward', kwargs: {data_name: "img"}}
  - {link_name: 'output-activation', method_name: 'forward', kwargs: {data_name: "img"}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img", pattern: "(b s) (h w) -> b s 1 h w", s: 16, h: 28, w: 28}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img_org", pattern: "b 1 h w -> b 1 1 h w"}}
  - {link_name: 'repeat', method_name: 'forward', kwargs: {data_name: "img_org", pattern: "b 1 1 h w -> b s 1 h w", s: 16}}
  - {link_name: 'reconstr_loss', method_name: 'forward', kwargs: {data_name: "img", target_name: "img_org", reduce_pattern: "b s 1 h w -> b s"}}
- command_name: "encode"
  processing_steps:
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img", pattern: "b 1 h w -> b (h w)"}}
  - {link_name: 'encoder', method_name: 'forward', kwargs: {data_name: "img"}}
  - {link_name: 'posterior', method_name: 'forward', kwargs: {data_name: "img", n_latent_samples: 1}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img", pattern: "b 1 d -> b d"}}
- command_name: "encode_decode"
  processing_steps:
  - {link_name: 'clone-input', method_name: 'forward', kwargs: {data_name: "img", clone_name: "img_org"}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img", pattern: "b 1 h w -> b (h w)"}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "condition_values", pattern: "b 1 -> b"}}
  - {link_name: 'encoder', method_name: 'forward', kwargs: {data_name: "img"}}
  - {link_name: 'posterior', method_name: 'forward', kwargs: {data_name: "img", n_latent_samples: 1}}
  - {link_name: 'prior', method_name: 'forward', kwargs: {data_name: "img", component_indicator_name: "condition_values"}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img", pattern: "b 1 d -> b d"}}
  - {link_name: 'decoder', method_name: 'forward', kwargs: {data_name: "img"}}
  - {link_name: 'output-activation', method_name: 'forward', kwargs: {data_name: "img"}}
  - {link_name: 'rearrange', method_name: 'forward', kwargs: {data_name: "img", pattern: "b (h w) -> b 1 h w", h: 28, w: 28},}

