# data configuration
first_modality_dim: 13953 # GEX | max 13953 | MAY BE CHANGED FOR DEBUGGING
second_modality_dim: 134 # ADT | max 134 | MAY BE CHANGED FOR DEBUGGING
subsample_frac: 1 # | MAY BE CHANGED FOR DEBUGGING
include_class_labels: True
# architecture configuration
omivae_implementation: "OmiGMPriorProbabilisticAE"
batch_norm: False #False
encoder_hidden_dim: 5000 #512
encoder_out_dim: 40 #128
latent_dim: 20
decoder_in_dim: 10 #128
decoder_hidden_dim: 20 #512
first_modality_hidden_dim: 50 #512
first_modality_embedding_dim: 50 #512
second_modality_hidden_dim: 10 #128
second_modality_embedding_dim: 10 #64
output_modelling_type: "mse_direct_reconstruction" # "mse_direct_reconstruction", "ll_neg_binomial"
no_components: 2
components_std: 1
no_latent_samples: 16
# classification specific configuration
classification_head: False
num_classes: 0
class_weights: null
# loss configuration
recon_loss_coef: 1
gmm_likelihood_loss_coef: 0.1
entropy_loss_coef: 0.1
# kld_loss_coef: 1
c_loss_coef: 1
# training configuration
batch_size: 128
lr: 0.001
max_epochs: 5
log_every_n_steps: 1
early_stopping: False
min_delta: 0.00001
patience: 5
# logger: True