model_name: "OmiAESimple"
# data configuration
first_modality_dim: 13953 # GEX | max 13953 | MAY BE CHANGED FOR DEBUGGING
second_modality_dim: 134 # ADT | max 134 | MAY BE CHANGED FOR DEBUGGING
subsample_frac: 1 # | MAY BE CHANGED FOR DEBUGGING
include_class_labels: False
normalize: True
remove_batch_effect: False
target_hierarchy_level: -1
# architecture configuration
omivae_implementation: "OmiAE"
batch_norm: False
dropout_rate: 0.0
encoder_hidden_dim: 50 #512
encoder_out_dim: 10 #128
latent_dim: 10
decoder_hidden_dim: 50 #512
output_modelling_type: "mse_direct_reconstruction" # "mse_direct_reconstruction", "ll_neg_binomial"
# classification specific configuration
classification_head: False
# loss configuration
recon_loss_coef: 1
c_loss_coef: 0.01
# training configuration
batch_size: 128
lr: 0.01
max_epochs: 10
log_every_n_steps: 1
early_stopping: False
min_delta: 0.01
patience: 5